name: Daily Commit

on:
  schedule:
    - cron: '30 5 * * *'  # Runs daily at 05:30 UTC
  workflow_dispatch:

jobs:
  commit-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update timestamp for 24f2006326@ds.study.iitm.ac.in
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
              - name: Update timestamp for 24f2006326@ds.study.iitm.ac.in
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          echo "Last run: $(date -u)" > last-run.txt
          git config --global user.name "GitHub Action"
          git config --global user.email "24f2006326@ds.study.iitm.ac.in"
          git add last-run.txt
          git commit -m "Daily commit: $(date -u)" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
          git push origin HEAD

